"""Template loading and rendering helpers for DesignerAgent."""

from __future__ import annotations

from pathlib import Path

from .frameworks import normalize_framework

TEMPLATE_FILE_BY_STYLE = {
    "tailwind": "landing_page.html",
    "bootstrap": "dashboard.html",
    "material": "blog_post.html",
    "custom": "admin_panel.html",
}

DEFAULT_TEMPLATE_PARAMS = {
    "title": "Generated UI",
    "heading": "Welcome",
    "subheading": "Generated with DesignerAgent",
    "cta_text": "Get Started",
    "body_text": "This layout was generated by rule-based templates.",
    "primary_color": "#2563EB",
    "background_color": "#F8FAFC",
}

FALLBACK_TEMPLATE = "<main><h1>{{title}}</h1><p>{{subheading}}</p></main>"


def pick_template_file(style: str) -> str:
    """Select template file by normalized style."""
    style_norm = normalize_framework(style)
    return TEMPLATE_FILE_BY_STYLE.get(style_norm, TEMPLATE_FILE_BY_STYLE["tailwind"])


def load_template(templates_dir: Path, file_name: str) -> str:
    """Load template from disk, fallback to minimal markup."""
    path = templates_dir / file_name
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        return FALLBACK_TEMPLATE


def render_template(template: str, params: dict[str, str]) -> str:
    """Simple placeholder replacement for {{key}} values."""
    rendered = template
    for key, value in params.items():
        rendered = rendered.replace(f"{{{{{key}}}}}", value)
    return rendered


def merge_template_params(params: dict[str, str] | None = None) -> dict[str, str]:
    """Merge default template params with caller-provided values."""
    merged = dict(DEFAULT_TEMPLATE_PARAMS)
    if params:
        for key, value in params.items():
            merged[str(key)] = str(value)
    return merged

